[package]
name = "gcp-apis"
version = "0.1.0"
authors = ["Max Seiden <max@sigmacomputing.io>"]

[dependencies]
hyper = "^ 0.10"
mime = "^ 0.2.0"
serde = "^ 0.9"
serde_json = "^ 0.9"
serde_derive = "^ 0.9"
yup-oauth2 = "^ 1.0"
url = "= 0.5"
