[package]
name = "gcp-apis"
version = "0.1.0"
authors = ["Max Seiden <max@sigmacomputing.io>"]

[dependencies]
hyper = "0.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
yup-oauth2 = "1.0"
url = "0.5"
